### ISSUE TITLE
WARNING  | TapSwap | [!] Error in auth: list index out of range

### ISSUE THREAD

**Issue by SannoV** [Poryaei/All-In-One#11]
Hi. That's the kind of problem that appeared today, what could it be related to?

![image](https://github.com/Poryaei/All-In-One/assets/45595167/571f61b6-57c8-4708-841f-ce0c94251d0d)

**Comment by SireJeff** [comment]
yeah same for me

**Comment by glushko** [comment]
++

**Comment by Poryaei** [comment]
Wait pls almost done

**Comment by Poryaei** [comment]
Ok

**Comment by Poryaei** [comment]
![image](https://github.com/Poryaei/All-In-One/assets/83473475/07b79298-7270-4b74-95fa-b6bd3e22dcb2)

**Comment by Poryaei** [comment]
Fixed!

**Comment by SannoV** [comment]
![image](https://github.com/Poryaei/All-In-One/assets/45595167/ce5d0bed-8019-4bf3-b87a-d8b2a51731a6)
After the update, there is now such an error. At the same time, the window closes almost immediately.

**Comment by Poryaei** [comment]
@SannoV use python 3.10

**Comment by Poryaei** [comment]
js2py has issues on Python 3.12.

**Comment by glushko** [comment]
Thx u, working 👍

**Comment by SannoV** [comment]
Everything is working now. Thank you very much!

**Comment by SannoV** [comment]
![image](https://github.com/Poryaei/All-In-One/assets/45595167/142a28aa-f3ed-4ade-93db-dab2d7ca217b)
Hi. This problem appeared again (Did the admins do something again?).
