### ISSUE TITLE
No module named 'scripts.tapswap'

### ISSUE THREAD

**Issue by jnoks66** [Poryaei/All-In-One#16]
C:\Users\root\Desktop\All-In-One-main>python app.py
Traceback (most recent call last):
  File "C:\Users\root\Desktop\All-In-One-main\app.py", line 5, in <module>
    from scripts.tapswap import TapSwap
ModuleNotFoundError: No module named 'scripts.tapswap'

I get this error when I start the bot

**Comment by Poryaei** [comment]
I think you don't have the scripts folder.

**Comment by Poryaei** [comment]
https://github.com/Poryaei/All-In-One/tree/main/scripts

**Comment by jnoks66** [comment]
I turned off the values ​​of tapswap and hamster kombat bot in the config file, could that be why?

**Comment by Poryaei** [comment]
No

**Comment by jnoks66** [comment]
![image](https://github.com/Poryaei/All-In-One/assets/71335852/db2e56c8-37d2-4c10-979b-4708f408c495)
There are no missing files in the scripts

**Comment by jnoks66** [comment]
What is your Python version? Let me try to run it on that version.

**Comment by Poryaei** [comment]
You deleted the scripts files!

**Comment by Poryaei** [comment]
Just change config.json for turn off

**Comment by jnoks66** [comment]
It's my fault, I'm sorry for wasting your time.

**Comment by Poryaei** [comment]
Don't say it like that! Feel free to ask if you have any questions, and if there's no problem, let's close the issue.
