### ISSUE TITLE
Есть ли проблема с тем, что бот не покупает некоторые карты?

### ISSUE THREAD

**Issue by EddieBrock69** [Poryaei/All-In-One#17]
Привет, пишу потому что в аналогах этого бота по какой-то причине не покупаются некоторые карты из раздела Specials в hamster kombat. Есть ли такая проблема в этом боте? Нет возможности самому проверить. Примеры таких карт: "Consensus Piranha Pass", "Bitcoin Pizza day", "Top 10 Global Ranking", "Special Hamster Conference".

**Comment by glushko** [comment]
DEBUG     | Hamster | [~] Updating: bitcoin_pizza_day | x_day_return: 121.01522842639594
Все работает смотрb на **max_days_for_return** это по факту лимит ROI
