### ISSUE TITLE
Hamster Miner

### ISSUE THREAD

**Issue by imrobotss** [Poryaei/All-In-One#2]
Salam Dadash Chetori Age Hamster Ro Ham Tanha Bezari Mesle Tapswap Mamnon MiSham Pv Telegramet Bastas

**Comment by imrobotss** [comment]
Link Bezar Donate Konim

**Comment by imrobotss** [comment]
@Poryaei

**Comment by Poryaei** [comment]
سلام. میتونی تنها هم استفاده کنی. فایل کانفیگ رو ادیت بزن

If you set any of the clickers (tapswap_clicker, hamster_clicker, cexio_clicker) to "off", the bot will not interact with that specific bot.

**Comment by imrobotss** [comment]
> سلام. میتونی تنها هم استفاده کنی. فایل کانفیگ رو ادیت بزن
> 
> If you set any of the clickers (tapswap_clicker, hamster_clicker, cexio_clicker) to "off", the bot will not interact with that specific bot.

دورت بگردم بلد بودم ادیت کنم حتما انجام میدادم @Poryaei
