### ISSUE TITLE
Module Not Found Error js2py 

### ISSUE THREAD

**Issue by pamskye** [Poryaei/All-In-One#23]
Trackback (last call):
"C:\Users\sbyte\Desktop\coin\All-In-One\multi-account.py" file, line 4,
import from scripts.tapswap TapSwap
File "C:\Users\sbyte\Desktop\coin\All-In-One\scripts\tapswap.py", line 8,
in js2py import
ModuleNotFoundError: No module named 'js2py'

I downloaded the file but I still get the same error

**Comment by K1ckMan** [comment]
Use Python 3.10
