### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nimakhooye2** [Poryaei/All-In-One#25]
![Screenshot_۲۰۲۴-۰۶-۱۴-۰۵-۴۲-۴۳-۲۰۷_com server auditor ssh client](https://github.com/Poryaei/All-In-One/assets/101529083/5711d6d8-3ccd-4aba-be9e-ade6489a1e5a)

**Comment by yuvar-edu** [comment]
Install requirements in requirements.txt "pip install -r requirements.txt"

**Comment by nimakhooye2** [comment]
All requirements are installed but I am facing these errors

**Comment by Poryaei** [comment]
Please update the code. 🔄
