### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by nimakhooye2** [Poryaei/All-In-One#27]
![Uploading Screenshot_۲۰۲۴-۰۶-۱۴-۰۷-۱۴-۱۴-۹۵۴_com.server.auditor.ssh.client.jpg…]()

**Comment by nimakhooye2** [comment]
![Screenshot_۲۰۲۴-۰۶-۱۴-۰۷-۱۴-۱۴-۹۵۴_com server auditor ssh client](https://github.com/Poryaei/All-In-One/assets/101529083/6f34f472-20c2-43dd-b2bb-7edb9abf7aae)

**Comment by Poryaei** [comment]
Please update the code. 🔄
