### ISSUE TITLE
i have no idea, it's got stuck and do nothing 

### ISSUE THREAD

**Issue by yopiucing** [Poryaei/All-In-One#30]
![IMG_20240615_025549](https://github.com/Poryaei/All-In-One/assets/116066417/678d01a3-a9e1-429e-ae7f-caa1d66e0a7e)

**Comment by Poryaei** [comment]
Add clients then run the bot

**Comment by yopiucing** [comment]
> Add clients then run the bot

already created 2 session

**Comment by Poryaei** [comment]
Please go to the cach folder and check how many files you have there?

**Comment by yopiucing** [comment]
> Please go to the cach folder and check how many files you have there?

nothing at all, should I delete the old session and then create a new session

**Comment by yopiucing** [comment]
> > Please go to the cach folder and check how many files you have there?
> 
> nothing at all, should I delete the old session and then create a new session

solved, thanks
