### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zahednia** [Poryaei/All-In-One#31]
i have brand new error :

WARNING  | 2024-06-15 08:40:40 | TapSwap | User: 1 | [!] Error in update headers: HTTPSConnectionPool(host='poeai.click', port=443): Max retries exceeded with url: /tapswap/headers.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b2529f290>: Failed to establish a new connection: [Errno 111] Connection refused'))

![image](https://github.com/Poryaei/All-In-One/assets/70833007/de6f7615-36b1-4f04-a382-2d5a0000e64b)

**Comment by salehpx** [comment]
same error here 

![image_2024-06-15_101413321](https://github.com/Poryaei/All-In-One/assets/138655139/3eac5d44-9728-428e-8d4e-ccde7a395889)

**Comment by salehpx** [comment]
After waiting for 2 minutes, the robot started working.
In fact, it was not a problem .

**Comment by zahednia** [comment]
> After waiting for 2 minutes, BOT started working. In fact, it was not a problem .

Me too, but immediately after starting the robot, it gets this state

**Comment by zahednia** [comment]
Did you solve the problem? 
@Poryaei

**Comment by Poryaei** [comment]
@zahednia The problem is with your internet connection! 🌐

The script should be able to fetch information from the following link:
https://poeai.click/tapswap/headers.json

**Comment by zahednia** [comment]
> @zahednia The problem is with your internet connection! 🌐
> 
> The script should be able to fetch information from the following link:
> https://poeai.click/tapswap/headers.json



 i run this in host 
how can i do ? 
i get another host ?

**Comment by Poryaei** [comment]
@zahednia 
سلام کوروش جان.
اگه مطمعن هستی هاست به لینک داده شده دسترسی نداره چند تا راه داری که یکیش عوض کردن سرویس دهنده هست
