### ISSUE TITLE
Error in Hamster Click: local variable 'sorted_upgrades' referenced before assignment

### ISSUE THREAD

**Issue by shadow-mafi** [Poryaei/All-In-One#35]
Hi thanks for your work i got this warning

WARNING  | 2024-06-15 18:57:01 | mainapp | User: 7106508894 | Error in Hamster Click: local variable 'sorted_upgrades' referenced before assignment

i also set max_days_return to 1 for not buying cards to only click 

![Screenshot 2024-06-15 215733](https://github.com/Poryaei/All-In-One/assets/93098536/64f95f92-a346-4493-bf9f-6d4f6b17495b)

**Comment by Poryaei** [comment]
Fixed
