### ISSUE TITLE
access_token

### ISSUE THREAD

**Issue by THMaST3R** [Poryaei/All-In-One#37]
WARNING  | 2024-06-16 09:42:08 | TapSwap | User: 1 | [!] There is no access_token in response
ERROR    | 2024-06-16 09:42:11 | TapSwap | User: 1 | [!] We ran into trouble with the get auth token! 🚫 The script is stopping.

**Comment by neeeeey** [comment]
Getting this issue as well

**Comment by Poryaei** [comment]
Fixed
