### ISSUE TITLE
Multi account

### ISSUE THREAD

**Issue by Kingprogrammer07** [Poryaei/All-In-One#38]
when i add my accounts it works but when i restart the multi-account file it gives 'ignoring'

**Comment by Poryaei** [comment]
Screen shot pls

**Comment by Kolesnikov-R** [comment]
Good afternoon, please advise, the question is as follows:
I added 2 accounts, ran the script multi-account.py
In the game: Hamster on the second account nothing is executed.  Other games on the two accounts work. 
In the bot, I get the log: Start Tapping ⛏️ every minute, is this normal ? 
When querying: /balance, I get statistics only for one account, the second account has no statistics. Is this how it should be ?

**Comment by Poryaei** [comment]
In the Multi Account bot, any command you send is executed for all accounts.
