### ISSUE TITLE
tapswap doesn't work

### ISSUE THREAD

**Issue by 1010000-1000001-1001001-1001110** [Poryaei/All-In-One#4]
hi i got warn or error on tapswap i think for that reason tapswap doesn't work can you help?

![image](https://github.com/Poryaei/All-In-One/assets/122735122/ead01f83-55f4-4b8e-87a1-63364b330deb)
![image](https://github.com/Poryaei/All-In-One/assets/122735122/9d2e9549-1228-42e3-b102-968987e01f9c)

**Comment by Poryaei** [comment]
fixed in the update!

**Comment by Poryaei** [comment]
It's true that there was a slight issue on the server side and the script wasn't working correctly, but there shouldn't be any problem now.
