### ISSUE TITLE
start tapping 

### ISSUE THREAD

**Issue by shadow-mafi** [Poryaei/All-In-One#40]
Hi there

just prints start tapping again and again

![Screenshot 2024-06-17 205724](https://github.com/Poryaei/All-In-One/assets/93098536/d4980719-0256-4d4f-92c8-a19533bea7d1)

**Comment by prohacker1024** [comment]
> Hi there
> 
> just prints start tapping again and again
> 
> ![Screenshot 2024-06-17 205724](https://private-user-images.githubusercontent.com/93098536/340406790-d4980719-0256-4d4f-92c8-a19533bea7d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDgwMTgsIm5iZiI6MTcxODY0NzcxOCwicGF0aCI6Ii85MzA5ODUzNi8zNDA0MDY3OTAtZDQ5ODA3MTktMDI1Ni00ZDRmLTkyYzgtYTE5NTMzYmVhN2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE4MDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNDNkMWQ2NDYyYThhMGM5OWMwZWJhNDVlNDVlZDYyMDczNTkxNTJlZTgxZWY4NWRmZTk2OGRhYzc5MDNlOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U0rT3kGOUuZPhyk2kS0m5SM0vZDyj33x0VDvqZjF9Dw)

then ,what is the problem ?

**Comment by shadow-mafi** [comment]
> > Hi there
> > just prints start tapping again and again
> > ![Screenshot 2024-06-17 205724](https://private-user-images.githubusercontent.com/93098536/340406790-d4980719-0256-4d4f-92c8-a19533bea7d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDgwMTgsIm5iZiI6MTcxODY0NzcxOCwicGF0aCI6Ii85MzA5ODUzNi8zNDA0MDY3OTAtZDQ5ODA3MTktMDI1Ni00ZDRmLTkyYzgtYTE5NTMzYmVhN2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE4MDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNDNkMWQ2NDYyYThhMGM5OWMwZWJhNDVlNDVlZDYyMDczNTkxNTJlZTgxZWY4NWRmZTk2OGRhYzc5MDNlOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U0rT3kGOUuZPhyk2kS0m5SM0vZDyj33x0VDvqZjF9Dw)
> 
> then ,what is the problem ?

It prints it every 2 min but not clicking , if its start clicking it prints clicks were succesfull and total coins earned like the first time is started the bot , i think its because the script cant detect if energy is full or not and prints start tapping again and again
