### ISSUE TITLE
Multi-account is not able to proceed with taps and updates since "next_hamster_click" is never set

### ISSUE THREAD

**Issue by k-pypin** [Poryaei/All-In-One#43]
`start_hamster_client` is trying to obtain `next_hamster_click` value from the cache and just returns if it is `None` or less then the current time.

The thing is - it is never set to an actual value.

**I believe that**
```
if next_hamster_click == None or time.time() < next_hamster_click:
        return
```

**should be changed to**

```
if next_hamster_click is not None and time.time() < next_hamster_click:
        return
```

**Comment by Poryaei** [comment]
Hello Thank you. You are right, the code has been updated.
