### ISSUE TITLE
HAMSTER Error in fetching Auth Token: Expecting value: line 1 column 1 (char 0). Retrying  

### ISSUE THREAD

**Issue by glushko** [Poryaei/All-In-One#44]
reason: 'Internal Server Error'

**Comment by glushko** [comment]
'Couchbase error! Method=query(q=\n      select auth_user.* from auth_user\n      where telegramUserId = $telegramUserId\n      limit 1\n      , options={"adhoc":false,"parameters":{"telegramUserId":****}}) Collection=hamster.auth.auth_user Error=InternalServerFailureError: internal server failure'

**Comment by glushko** [comment]
I think, they got the same error 
https://github.com/shamhi/HamsterKombatBot/issues/338#issuecomment-2179512441

**Comment by xshayank** [comment]
Yea
They updated their api

**Comment by glushko** [comment]
@xshayank mb you have some advice) ? how to fix 😄

**Comment by xshayank** [comment]
Yea I am looking into it
If I found smt I let you know

**Comment by Poryaei** [comment]
The problem was on their side!

**Comment by Poryaei** [comment]
> internal server failure
> Couchbase error

**Comment by d4rk5eed** [comment]
@glushko try to checkout 41b9712 commit . It worked for me on hamster
