### ISSUE TITLE
Cex_IO for multi-account.py Don't run do_tasks

### ISSUE THREAD

**Issue by glushko** [Poryaei/All-In-One#45]
You forgot to add `Thread(target=cex_io_client.do_tasks).start()` or something like this

**Comment by glushko** [comment]
BTW I see 
`ERROR    | 2024-06-20 03:15:40 | CexIO | User: **** | Error in response: {'status': 'error', 'data': {'reason': 'Task is not at NONE state'}}`
When try to run `do_tasks`
For me this resolve the problem 
![image](https://github.com/Poryaei/All-In-One/assets/4244787/70f41ac7-c6e1-4c28-b9b6-e01d7e09051c)

**Comment by Poryaei** [comment]
You got it! I'll add it soon.
