### ISSUE TITLE
Add More Game

### ISSUE THREAD

**Issue by mrdarkerr** [Poryaei/All-In-One#47]
!!! [w-coin ](https://t.me/wcoin_tapbot?start=NTYxNzU3MTIwNg==)
[prick ](https://t.me/wcoin_tapbot?start=NTYxNzU3MTIwNg==)
[cedex_tap_bot](https://t.me/cedex_tap_bot)
[TheBaboon_Bot](https://t.me/TheBaboon_Bot/start?startapp=_5617571206)
[pixelversexyzbot](https://t.me/pixelversexyzbot?start=5617571206)
[gamee](https://t.me/gamee?start=ref_5617571206)
[cedex_tap_bot](https://t.me/cedex_tap_bot?start=1718630244634688)
!!! [BlumCryptoBot](https://t.me/BlumCryptoBot/app?startapp=ref_XpcIYSqz9f)
[seed_coin_bot](https://t.me/seed_coin_bot/app?startapp=466310508)
[geMzcoin_bot](https://t.me/geMzcoin_bot/play_gemz_now?startapp=VYafE-UGGa2Z0VoXGVQzvg)
!!! [herewalletbot](https://t.me/herewalletbot/app?startapp=11894445)

Chrome extension : Ignore X-Frame-Options

**Comment by THMaST3R** [comment]
did u just saying this bcz of referral? 😂

**Comment by Poryaei** [comment]
Sure
