### ISSUE TITLE
Hamster Automatic updates cards

### ISSUE THREAD

**Issue by B0ND07** [Poryaei/All-In-One#48]
How to turn off Automatic updates cards

**Comment by mrdarkerr** [comment]
Probably this value in the config file 
`"auto_upgrade": True",`

**Comment by B0ND07** [comment]
> Probably this value in the config file `"auto_upgrade": True",`

It's not working

**Comment by salehpx** [comment]
Edit max_days_for_return in config.json to 1

**Comment by Poryaei** [comment]
Thanks @salehpx
