### ISSUE TITLE
TapSwap

### ISSUE THREAD

**Issue by loltt** [Poryaei/All-In-One#49]
INFO     | 2024-06-21 20:18:39 | mainapp | Client is Ready!
WARNING  | 2024-06-21 20:18:40 | TapSwap | User: 1 | [!] Error in auth: Header part (1) from ('x-touch', 1) must be of type str or bytes, not <class 'int'>
WARNING  | 2024-06-21 20:18:43 | TapSwap | User: 1 | [!] Error in auth: Header part (1) from ('x-touch', 1) must be of type str or bytes, not <class 'int'>
WARNING  | 2024-06-21 20:18:46 | TapSwap | User: 1 | [!] Error in auth: Header part (1) from ('x-touch', 1) must be of type str or bytes, not <class 'int'>
WARNING  | 2024-06-21 20:18:49 | TapSwap | User: 1 | [!] Error in auth: Header part (1) from ('x-touch', 1) must be of type str or bytes, not <class 'int'>
WARNING  | 2024-06-21 20:18:52 | TapSwap | User: 1 | [!] Error in auth: Header part (1) from ('x-touch', 1) must be of type str or bytes, not <class 'int'>
WARNING  | 2024-06-21 20:18:56 | TapSwap | User: 1 | [!] Error in auth: Header part (1) from ('x-touch', 1) must be of type str or bytes, not <class 'int'>
WARNING  | 2024-06-21 20:18:59 | TapSwap | User: 1 | [!] Error in auth: Header part (1) from ('x-touch', 1) must be of type str or bytes, not <class 'int'>
WARNING  | 2024-06-21 20:19:02 | TapSwap | User: 1 | [!] Error in auth: Header part (1) from ('x-touch', 1) must be of type str or bytes, not <class 'int'>
ERROR    | 2024-06-21 20:19:05 | TapSwap | User: 1 | [!] We ran into trouble with the get auth token! 🚫The class is not ready.
Oh and tapswap.py was changed by new

**Comment by Poryaei** [comment]
Fixed
