### ISSUE TITLE
error

### ISSUE THREAD

**Issue by abolfazlMKazemi** [Poryaei/All-In-One#5]
Hi thanks for this code i get this error
WARNING  | TapSwap | [!] Error in auth: Expecting value: line 1 column 1 (char 0)
WARNING  | TapSwap | [!] Error in auth: Expecting value: line 1 column 1 (char 0)
WARNING  | TapSwap | [!] Error in auth: Expecting value: line 1 column 1 (char 0)
WARNING  | TapSwap | [!] Error in auth: Expecting value: line 1 column 1 (char 0)
WARNING  | TapSwap | [!] Error in auth: Expecting value: line 1 column 1 (char 0)
WARNING  | TapSwap | [!] Error in auth: Expecting value: line 1 column 1 (char 0)
WARNING  | TapSwap | [!] Error in auth: Expecting value: line 1 column 1 (char 0)
WARNING  | TapSwap | [!] Error in auth: Expecting value: line 1 column 1 (char 0)
ERROR    | TapSwap | [!] We ran into trouble with the get auth token! 🚫 The script is stopping.

**Comment by Poryaei** [comment]
https://t.me/tapswapai/121
