### ISSUE TITLE
There is no access_token in response

### ISSUE THREAD

**Issue by mrdarkerr** [Poryaei/All-In-One#52]
INFO     | 2024-06-21 17:29:25 | TapSwap | User: 5637571206 | [~] ByPass CHQ:  538830
{'statusCode': 400, 'message': 'invalid_chr[2]'}
WARNING  | 2024-06-21 17:29:25 | TapSwap | User: 5637571206 | [!] There is no access_token in response

**Comment by Poryaei** [comment]
Fixed
