### ISSUE TITLE
You Blocked This User / Error

### ISSUE THREAD

**Issue by danazor** [Poryaei/All-In-One#53]
Hello, i get this error. Idk how to fix it. Can you help me please? Thanks!
![image](https://github.com/Poryaei/All-In-One/assets/52712010/fa12f110-c49e-43e5-b3f4-b62b54a5560f)

**Comment by Poryaei** [comment]
Start hamster bot

**Comment by danazor** [comment]
> Start hamster bot

thanks!

**Comment by danazor** [comment]
@Poryaei sorry if i bored you. Now i get access token error
![image](https://github.com/Poryaei/All-In-One/assets/52712010/5d77a5ae-e843-4875-a0e1-8a607c4256d5)

**Comment by Poryaei** [comment]
https://github.com/Poryaei/All-In-One/blob/main/app.py

Update pls

**Comment by danazor** [comment]
> https://github.com/Poryaei/All-In-One/blob/main/app.py
> 
> Update pls

thank you so much, it works
