### ISSUE TITLE
Error extracting CHQ result: Expecting value: line 1 column 1 

### ISSUE THREAD

**Issue by XiteZReal** [Poryaei/All-In-One#56]
warning code : **`WARNING  | 2024-06-22 09:04:30 | TapSwap | User: * | [!] Error extracting CHQ result: Expecting value: line 1 column 1 (char 0)`**

**Comment by zahednia** [comment]
me too
@Poryaei

**Comment by AbbyTheGod** [comment]
Update Your app.py

**Comment by XiteZReal** [comment]
![image](https://github.com/Poryaei/All-In-One/assets/86098669/2712fa52-8676-4500-b991-768df4a35845)
again...

**Comment by THMaST3R** [comment]
same here

**Comment by THMaST3R** [comment]
@Poryaei can u pls update this too?
https://github.com/Poryaei/TapSwap-Clicker

**Comment by zahednia** [comment]
i have this error to my friend 

@Poryaei

**Comment by ElyasMoshirpanahi** [comment]
@AbbyTheGod 
@Poryaei 
![image](https://github.com/Poryaei/All-In-One/assets/37846222/e8459d7c-3b2c-4114-84e3-72941c966acf)
Same problem with App.py as well as multi-account.py

**Comment by Kingprogrammer07** [comment]
me too

**Comment by lord8585** [comment]
@Poryaei same here

**Comment by trunghuyne** [comment]
me too

**Comment by ElyasMoshirpanahi** [comment]
@Poryaei if you can guide us how we debug the code maybe we also can collaborate

**Comment by Poryaei** [comment]
They used a mathematical/non-mathematical relationship for each person that I don't know what it is about! I'm trying to figure it out.

**Comment by trunghuyne** [comment]
![image](https://github.com/Poryaei/All-In-One/assets/119916277/c54439e5-5fb0-4567-9363-7f0a2a5e9aeb)

**Comment by THMaST3R** [comment]
@trunghuyne Have you ever used autoclicker apps before? I have used @Poryaei codes since the beginning and i have not been banned yet

**Comment by XiteZReal** [comment]
> @trunghuyne Have you ever used autoclicker apps before? I have used @Poryaei codes since the beginning and i have not been banned yet

Me too

**Comment by d4rk5eed** [comment]
@Poryaei need hlp? publish the problem - maybe collective brain can assist

**Comment by trunghuyne** [comment]
@THMaST3R  I found out if I bypass the fixed web tele. I can access it by opening it on my mobile.
