### ISSUE TITLE
Blum can't claim daily reward

### ISSUE THREAD

**Issue by glushko** [Poryaei/All-In-One#65]
```
ERROR    | 2024-07-12 13:27:05 | Blum | User:** | Request to https://game-domain.blum.codes/api/v1/daily-reward?offset=-210 failed: 404 Client Error: Not Found for url: https://game-domain.blum.codes/api/v1/daily-reward?offset=-210 | 
{"message":"Not Found"}
ERROR    | 2024-07-12 13:27:10 | Blum | User: ** | Request to https://game-domain.blum.codes/api/v1/daily-reward failed: 400 Client Error: Bad Request for url: https://game-domain.blum.codes/api/v1/daily-reward |
 {"message":"same day"}
```
Btw mb I do something wrong, can u have advice

**Comment by sonaxpro** [comment]
I have the same error.
I think the problem is with the Blum servers.
We need to wait for a long time and we get a Timeout or 404 error.
I think the script should try again later.
But I'm not sure.

**Comment by glushko** [comment]
I guess it's not working, I have waited more than 2 days and collection not working (only login, and save subsequence of days)

**Comment by glushko** [comment]
I checked it whole week and right now I see, it's working, thx everyone
