### ISSUE TITLE
RockyRabbit^ Request

### ISSUE THREAD

**Issue by laggedv1** [Poryaei/All-In-One#66]
Hi, first thanks for doing rockyrabbit* bot.

Tap and upgrade works, im just not gettin my claims made on "claim" section can you add it ?

**Comment by glushko** [comment]
Yea, I have seen this problem too, but u can just call `do_daily_tasks`, and it will be work )

**Comment by laggedv1** [comment]
could you give me example in code?
def do_daily_tasks(self.    ?

**Comment by glushko** [comment]
> could you give me example in code? def do_daily_tasks(self. ?

Should work 
![image](https://github.com/user-attachments/assets/5368578a-4f90-4842-a160-d9fdea9b65c2)

**Comment by glushko** [comment]
Fun `do_daily_task` have been add by owner in first iteration

**Comment by laggedv1** [comment]
added rabbit_client.do_daily_tasks() doesnt seem to work 

![imagen](https://github.com/user-attachments/assets/be79973b-0222-4c21-87f7-791383fddf02)

**Comment by glushko** [comment]
Sorry, I will be check it later (today)

> added rabbit_client.do_daily_tasks() doesnt seem to work
> 
> ![imagen](https://private-user-images.githubusercontent.com/174215942/348889082-be79973b-0222-4c21-87f7-791383fddf02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjIzNzMsIm5iZiI6MTcyMTEyMjA3MywicGF0aCI6Ii8xNzQyMTU5NDIvMzQ4ODg5MDgyLWJlNzk5NzNiLTAyMjItNGMyMS04N2Y3LTc5MTM4M2ZkZGYwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwOTI3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTFiZWQ5MmZlYmZhY2FmYTRmZGQwY2UxNmI5NDI4N2I2ZTU4MmI0OTJlNzk5NWRiMTRhZWY1YjRhOTNlNDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VUt7_k1imIO5LvSKugoZ4jCau-HkEpHEsxD0zgTeWcE)

**Comment by glushko** [comment]
> added rabbit_client.do_daily_tasks() doesnt seem to work
> 
> ![imagen](https://private-user-images.githubusercontent.com/174215942/348889082-be79973b-0222-4c21-87f7-791383fddf02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjI0OTEsIm5iZiI6MTcyMTEyMjE5MSwicGF0aCI6Ii8xNzQyMTU5NDIvMzQ4ODg5MDgyLWJlNzk5NzNiLTAyMjItNGMyMS04N2Y3LTc5MTM4M2ZkZGYwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwOTI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODBmYzgzYjA5ZWQ3Y2Q0M2ExMTdhNWRhMmU1Yzk2NWRhOTAzY2Y1N2Q2YjlhMjQ2MDA1YjVmOGYwM2Y0ODZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dFJVaF38wOxO7-PyZYV29K8gSOc9rv6rAMq-NYAQ2ZA)

U sure your code run this ? (I mean before u have some condition, and it can be false, and not run)  can u delete from cache rabbit timers and add more logs (like `print("test")`)

**Comment by laggedv1** [comment]
> > added rabbit_client.do_daily_tasks() doesnt seem to work
> > ![imagen](https://private-user-images.githubusercontent.com/174215942/348889082-be79973b-0222-4c21-87f7-791383fddf02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjI0OTEsIm5iZiI6MTcyMTEyMjE5MSwicGF0aCI6Ii8xNzQyMTU5NDIvMzQ4ODg5MDgyLWJlNzk5NzNiLTAyMjItNGMyMS04N2Y3LTc5MTM4M2ZkZGYwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwOTI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODBmYzgzYjA5ZWQ3Y2Q0M2ExMTdhNWRhMmU1Yzk2NWRhOTAzY2Y1N2Q2YjlhMjQ2MDA1YjVmOGYwM2Y0ODZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dFJVaF38wOxO7-PyZYV29K8gSOc9rv6rAMq-NYAQ2ZA)
> 
> U sure your code run this ? (I mean before u have some condition, and it can be false, and not run) can u delete from cache rabbit timers and add more logs (like `print("test")`)

Sorry was busy thanks for your help, gonna try today & tell you

**Comment by laggedv1** [comment]
it works perfect now i was drunk doing changes under rockyrabbit.py file instead of send_taps 

ty bro
