### ISSUE TITLE
Cant receive Telegram code...

### ISSUE THREAD

**Issue by mark522412** [Poryaei/All-In-One#68]
I enter my phone number and no code comes to my telegram account. bot token doesn't work either

Persian:
حاجی شماره که میزنم کد نمیاد تو تلگرام گوشیم. اون بات توکن هم که میزنم یه ارور میده میگه :
Traceback (most recent call last):
  File "C:\...\aio\All-In-One\multi-account.py", line 93, in <module>
    url_files = [f for f in os.listdir('cache') if f.endswith('.json')]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'cache'

**Comment by glushko** [comment]
U sure phone was right ? U should use phone number with code of country (like this +1801112233)

**Comment by mark522412** [comment]
> U sure phone was right ? U should use phone number with code of country (like this +1801112233)

Yes. I've done this before with other bots i know how this works...BUT.. i checked it again now its working! it shows some errors but i think it is working now. 
closing the issue. thanks for the answer
