### ISSUE TITLE
mini game

### ISSUE THREAD

**Issue by Kingprogrammer07** [Poryaei/All-In-One#71]
do you code for the hamster mini game too?

**Comment by AlexanderQueen** [comment]
I think the thread is dead and dev don't care. @Poryaei

**Comment by khosrowkhazraei** [comment]
@Kingprogrammer07 Due to the unauthorized copying of this repository by another individual, the author has decided to discontinue development.

**Comment by Poryaei** [comment]
@Kingprogrammer07 check update
