### ISSUE TITLE
Hamster TAP ( Hamster check: 'clickerUser')

### ISSUE THREAD

**Issue by glushko** [Poryaei/All-In-One#72]
If your bot, show this:

` ** | Error in Hamster check: 'clickerUser'`

Just update function **tap** in **hamster.py** like this

```
    def tap(self, count: int, available_taps: int = 5500):
        timex = (int)(time.time())
        payload = {"count": count,
                   "availableTaps": available_taps, "timestamp": timex}
        return self._post_request('/clicker/tap', payload)

```

**Comment by glushko** [comment]
> Thx a lot. But last line must be edited:
> 
> `return self._post_request('/clicker/tap', payload)` to this: `return self.post_request('/clicker/tap', payload)`

Yea sorry this fault, I changed lightly this class and fogot (

**Comment by Poryaei** [comment]
Thanks @glushko
