### ISSUE TITLE
new links

### ISSUE THREAD

**Issue by OghabTeam** [Poryaei/All-In-One#74]
Hello, I think the link of bots like Hamster and Blum has changed and also the bot in tapswap doesn't work at all and doesn't collect coins, please give an update, thanks.

![Screenshot 2024-08-03 140644](https://github.com/user-attachments/assets/ff03702d-fe93-4132-a35a-4a0bd5062075)

**Comment by khosrowkhazraei** [comment]
same error in hamster
INFO     | 2024-08-03 18:13:00 | Hamster | User: -------| Auth Token fetched successfully.
ERROR    | 2024-08-03 18:13:02 | tapper | Error in building client[--------.json]: division by zero

**Comment by Poryaei** [comment]
Hello Mehdi,

I have fixed the hamster issue. For the Bloom bot, those requests need to be sent so that it grants the daily ticket for the game. Don't pay too much attention to its errors.

And the Tap Swap bot is not working.
