### ISSUE TITLE
ERROR    | 2024-08-04 02:52:18 | tapper | Error in building Hamster[5########.json]: division by zero

### ISSUE THREAD

**Issue by Mahnazmohammadii** [Poryaei/All-In-One#75]
hi dear devolper 
دوست عزیز و گرامی با تشکز از زخمات شما متاسفانه با پدیت جدید کلیکر همستر کار نمیکنه ظاهرا انلاین میمونه اما کار نمیکنه 
ممنون میشم بررسی کنید 

ERROR    | 2024-08-04 02:52:18 | tapper | Error in building Hamster[5#######.json]: division by zero
DEBUG    | 2024-08-04 02:53:00 | tapper | Starting: 5#######
DEBUG    | 2024-08-04 02:54:00 | tapper | Starting: 5#######
DEBUG    | 2024-08-04 02:55:00 | tapper | Starting: 5#######

**Comment by Poryaei** [comment]
Fixed
