### ISSUE TITLE
No Detail Balance on All-In-One (MA) Collector Bot

### ISSUE THREAD

**Issue by khosrowkhazraei** [Poryaei/All-In-One#77]
![image](https://github.com/user-attachments/assets/45347c8f-ca55-4f67-9ff2-ac06f615af89)

The bot on the telegram, only shows main balance of Hamster, but not the rest

**Comment by glushko** [comment]
How we can see, it happened when added RRabbit https://github.com/Poryaei/All-In-One/commit/dc5ce8363b1a2810a2304f36affe2a7fe51dcd0f
Why, I don't know )  mb it lightly difficult support 
BTW u can add what u need, just by 2-3 line of code

**Comment by khosrowkhazraei** [comment]
just a clean clone, solved the issue.
