### ISSUE TITLE
FloodWaitError caused by ResolveUsernameRequest

### ISSUE THREAD

**Issue by nickyharpor** [Poryaei/All-In-One#9]
Hi @Poryaei. Thanks for the hard work. I really appreciate it.

I get `telethon.errors.rpcerrorlist.FloodWaitError: A wait of X seconds is required (caused by ResolveUsernameRequest)` on line 68 or 69 of `app.py` on some of my accounts the first time I run the app. Looks like you try to send messages to the bots without any sleeping here in https://github.com/Poryaei/All-In-One/blob/1c13c0b861cad5f1ec2214ae071f3636d1469d48/app.py#L68

It's not a big problem at all. It resolves by itself after waiting a few minutes. However, the app crashes after this exception is thrown. I think it's a good idea if you catch the exception and wait a short time between resolves.

**Comment by Poryaei** [comment]
Hello, thank you! 

It will be fixed in the upcoming update.
